# Generated by Django 2.2 on 2019-05-17 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_auto_20190517_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='student_quantity',
        ),
    ]
