# Generated by Django 2.2 on 2019-05-17 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_remove_class_student_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='shift',
        ),
    ]
