# Generated by Django 2.2 on 2019-05-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_remove_course_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
