# Generated by Django 2.2 on 2019-05-18 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0005_course_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='last_name',
            new_name='modality',
        ),
    ]
