# Generated by Django 2.2 on 2019-05-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0006_auto_20190518_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='shift',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
